### ISSUE TITLE
Perturbations for boolean data

### ISSUE THREAD

**Issue by Michael-Hollins** [AI-Explanation-Group-Project/xaiunits#86]
I've been trying to think of/write a test for the perturb function for Boolean data.

I wrote this:

def test_gaussian_noise_application():
   A, B, C = sympy.symbols('A B C')
   formula = Or(And(A, Not(B)), And(Not(A), C))
   dataset = BooleanDataset(formula=formula, n_samples=100)
   original_samples = dataset.samples.clone()  # Make a copy of the original samples

   perturbed_func = dataset.perturb_function(noise_scale=0.1, cat_resample_prob=0.0)
   perturbed_samples, _ = perturbed_func(dataset.samples)

    # Ensure perturbed_samples is actually a tensor and not part of a tuple
   if isinstance(perturbed_samples, tuple):
        perturbed_samples = perturbed_samples[0]  # Assuming the first element is the tensor of perturbed samples

    # Check that changes are within expected bounds (3*std dev for 99.7% confidence)
   noise_bound = 0.1 * 3
   differences = torch.abs(perturbed_samples - original_samples)
   assert torch.all(differences <= noise_bound), "Noise applied should not exceed expected bounds"
    
 This returns all zeros... But, thinking about it, what does it mean to perturb a Boolean value? Note: applying the default perturb function i.e. perturbed_func = dataset.perturb_function() returns perturbed samples containing 2s, which have no meaning in a Boolean context...? Is this an issue?

**Comment by BoredomCuzThis** [comment]
The perturbation function will use resampling for as perturbation, so if used correctly, all columns should be resampled by a probably specified, there will be no gaussian noise provided. 

Let me have a look

**Comment by BoredomCuzThis** [comment]
Based on the code and output; the function is working as intended.  The first output is the input, the 2nd is the perturbed inputs if the resampling is set to 1; i.e. 100% will be replaced. The 2nd is with resampling set to 0.5; so 50% of the time will be resampled (independently). 

For ease of understanding I will remove the noise_scale for the boolean since there isn't any continuous feature

![image](https://github.com/AI-Explanation-Group-Project/xaiunits/assets/88236741/ecfbdc0d-28b0-4f45-bfff-5beb6aa78ca6)
![image](https://github.com/AI-Explanation-Group-Project/xaiunits/assets/88236741/0f6521dc-c23b-47f4-bed9-670a80f8f248)
![image](https://github.com/AI-Explanation-Group-Project/xaiunits/assets/88236741/d27a4783-df2d-4a92-9370-544fb7b888c3)
